name: build_flavor
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^3.6.0
#  firebase_messaging: ^15.1.3
#  flutter_local_notifications: ^17.2.3
  firebase_remote_config: ^5.1.3

  firebase_analytics: ^11.3.3

  flutter_bloc: ^8.1.6

  tuple: ^2.0.2

  freezed_annotation: ^2.4.4

  # JsonParser
  json_annotation: ^4.9.0

  # Http Client
  dio: ^5.7.0

  #Svg Loader
  flutter_svg: ^2.0.10+1

  # Local Persist
  shared_preferences:

  # Simple direct Service Locator
  get_it: ^8.0.0

  # A collection of utilities to transform and manipulate streams.
  stream_transform: ^2.0.0

  #auth_nav
  auth_nav:
    git:
      url: https://github.com/thanhnguyen1121/auth_nav
      ref: master


  oauth2_dio:
    git:
      url: https://github.com/thanhnguyen1121/oauth2_dio
      ref: feature/update_dio_5.0

  collection: 1.18.0

  path_provider: ^2.1.1

  pull_to_refresh: ^2.0.0

  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  flutter_gen_runner: ^5.7.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
